version: "3"

volumes:
  wrr_norcal_local_postgres_data: {}
  wrr_norcal_local_postgres_data_backups: {}

services:
  django: &django
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: wrr_norcal_local_django
    container_name: wrr_norcal_local_django
    platform: linux/x86_64
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/usr/src/app:z
    environment:
      # Docker
      USE_DOCKER: "yes"
      IPYTHONDIR: "usr/src/app/.ipython"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_FLOWER_USER: "${CELERY_FLOWER_USER}"
      CELERY_FLOWER_PASSWORD: "${CELERY_FLOWER_PASSWORD}"
      # Postgres
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "wrr_norcal"
      POSTGRESS_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: wrr_norcal_production_postgres
    container_name: wrr_norcal_local_postgres
    volumes:
      - wrr_norcal_local_postgres_data:/var/lib/postgresql/data:Z
      - wrr_norcal_local_postgres_data_backups:/backups:z
    environment:
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432
      POSTGRES_DB: "wrr_norcal"
      POSTGRESS_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  docs:
    image: wrr_norcal_local_docs
    container_name: wrr_norcal_local_docs
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    environment:
      # Docker
      USE_DOCKER: "yes"
      IPYTHONDIR: "usr/src/app/.ipython"
      REDIS_URL: "redis://redis:6379/0"
      CELERY_FLOWER_USER: "${CELERY_FLOWER_USER}"
      CELERY_FLOWER_PASSWORD: "${CELERY_FLOWER_PASSWORD}"
    volumes:
      - ./docs:/docs:z
      - ./config:/usr/src/app/config:z
      - ./wrr_norcal:/usr/src/app/wrr_norcal:z
    ports:
      - "9000:9000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: wrr_norcal_local_mailhog
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MAILHOG_MAILER: "smtp"
      MAILHOG_HOST: "mailhog"
      MAILHOG_PORT: 1025
      MAILHOG_USER: null
      MAILHOG_PASSWD: null
      MAILHOG_ENCRYPTION: null

  redis:
    image: redis:6
    container_name: wrr_norcal_local_redis

  celeryworker:
    <<: *django
    image: wrr_norcal_local_celeryworker
    container_name: wrr_norcal_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: wrr_norcal_local_celerybeat
    container_name: wrr_norcal_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: wrr_norcal_local_flower
    container_name: wrr_norcal_local_flower
    ports:
      - "5555:5555"
    command: /start-flower
